version: '3.7'
services:
  service1:
    image: 127.0.01:4999/service1
    build: ./service1
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        #deploy:
        #replicas: 2
    environment:
      DATABASE_URI: ${DATABASE_URI}
  service2:
    image: 127.0.01:4999/service2      
    build: ./service2
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
        #deploy:
        #replicas: 2
  
  database: 
    image: mysql:5.7
    ports:
      - target: 3306
        published: 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: animal
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql

volumes:
  database-volume:        
